[build]
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  # Pin build to Node 20.x (LTS)
  NODE_VERSION = "20"
  # Increase npm timeout
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"
