[build]
  command = "bun install && bun run build"
  publish = ".next"

[build.environment]
  # Pin build to Node 20.x (LTS)
  NODE_VERSION = "20"
  # Use Bun for package management
  NPM_FLAGS = "--version" # This prevents npm from being used
